"""Initial migration

Revision ID: d5666b464afc
Revises: 
Create Date: 2025-02-19 01:06:39.857838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5666b464afc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uq_user_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('uq_user_username', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['uq_user_username'])
        batch_op.create_unique_constraint(None, ['uq_user_email'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uq_user_username')
        batch_op.drop_column('uq_user_email')

    # ### end Alembic commands ###
